name: Plinkd
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_maps_flutter: ^0.5.13
  dio: 2.1.0
  screen: ^0.0.5
  #  flutter_ringtone_player: ^1.0.0
  cupertino_icons: ^0.1.2
  page_view_indicator: ^1.0.1
  image_picker: ^0.5.0+6
  image_cropper: ^1.0.0
  #  flutter_places_dialog: ^1.0.2
  google_places_picker: ^0.1.0
  #  connectivity: ^0.4.2
  pull_to_refresh: 1.1.6
  device_id: ^0.1.3
  cached_network_image: 0.6.0
  flutter_html: ^0.9.4
  #  photo: ^0.2.0
  timeago: ^2.0.10
  intl: ">=0.14.0"
  photo_manager: ^0.3.4
  permission_handler: ^3.1.0
  package_info: ^0.4.0+3
  ntp: ^1.0.3
  country_pickers: ^1.0.2
  thumbnails: ^1.0.1
  photo_view: 0.2.1
  clipboard_manager: ^0.0.4
  flutter_staggered_grid_view: ^0.2.7
  #  flutter_document_picker: ^3.0.0
  file_picker: ^1.3.0
  open_file: ^2.0.1+1
  flutter_simple_video_player: ^0.0.9
  flutter_datetime_picker: 1.2.1
  uuid: 2.0.0
  path: any
  url_launcher: ^5.0.1


  #  flutter_ravepay: ^0.2.0
  #  audio_recorder: ^0.0.6
  keyboard_visibility: any
  emoji_picker: ^0.0.2
  filesize: ^1.0.1
  progress_hud: ^1.1.0
  cloud_firestore: ^0.12.1
  #  firebase_analytics: ^1.0.4
  firebase_storage: ^3.0.0
  firebase_auth: any



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/album.png
    - assets/icons/ic_launcher.png
    - assets/images/google_map_ta.png
    - assets/images/getstarted.png
    - assets/images/logo_text.png

  fonts:
    - family: Poppin
      fonts:
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf


